# Generated by Django 4.2.6 on 2023-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="payment",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="influencer",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="terms_and_conditions",
        ),
        migrations.RemoveField(
            model_name="engagement",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="engagement",
            name="influencer",
        ),
        migrations.RemoveField(
            model_name="engagement",
            name="performance",
        ),
        migrations.AddField(
            model_name="engagement",
            name="notes",
            field=models.CharField(default="YourDefaultValueHere", max_length=100),
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.DeleteModel(
            name="Influencer",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
