# Generated by Django 4.2.6 on 2023-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("influencer_app", "0008_campaign_brand_engagement_brand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="engagement",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="brand",
        ),
    ]
