# Generated by Django 4.2.6 on 2023-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer_app", "0010_alldata_delete_brand_delete_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alldata",
            name="termsConditionsInfo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
